config/routes.rb
Soapbox::Application.routes.draw do
  devise_for :users

  resource :account, only: [:show, :edit, :update]
  
  resources :pages, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :file_sections, only: [:edit, :create, :update, :destroy]
  end

end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		if user.is_a? User then
			if user.administrator then
				# logged in, is an admin
				can :manage, :all
			else
				# logged in, not an admin
				can :manage, Page do |page|
					page.account.user_id == user.id
				end
				can :manage, FileSection do |file_section|
					file_section.page.account.user_id == user.id
				end
			end
		else
			# not logged in

		end
		# Define abilities for the passed in user here. For example:
		#
		#   user ||= User.new # guest user (not logged in)
		#   if user.admin?
		#     can :manage, :all
		#   else
		#     can :read, :all
		#   end
		#
		# The first argument to `can` is the action you are giving the user permission to do.
		# If you pass :manage it will apply to every action. Other common actions here are
		# :read, :create, :update and :destroy.
		#
		# The second argument is the resource the user can perform the action on. If you pass
		# :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
		#
		# The third argument is an optional hash of conditions to further filter the objects.
		# For example, here the user can only update published articles.
		#
		#   can :update, Article, :published => true
		#
		# See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
	end
end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user
	has_many :pages, dependent: :destroy

	validates :subscription_tier, :user_id, presence: true
end

app/models/file_section.rb
class FileSection < ActiveRecord::Base
  attr_accessible :rank, :title
  
  belongs_to :page

  validates :page_id, :rank, :title, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :contact_available, :description, :subtitle, :title, :url, :main_image

  has_attached_file :main_image, :styles => { :banner => "1200" }, :default_url => "/admin_uploads/default_main_image.jpg", path: "/#{ENV['S3_PATH_PREFIX']}:class/:attachment/:id_partition/:style/:hash.:extension"

  process_in_background :main_image, processing_image_url: "https://s3.amazonaws.com/soapboxapp/admin_uploads/processing-img.png"

  validates_attachment :main_image, :content_type => { :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] }, :size => { :in => 0..500.kilobytes }

  belongs_to :account
  has_many :file_sections, dependent: :destroy

  validates :account_id, :url, presence: true
  validates :url, uniqueness: true

  def to_param
  	self.url
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable, :timeoutable
  # soon: :confirmable, :lockable, :recoverable, :omniauthable
  # maybe: :token_authenticatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  has_one :account, dependent: :destroy

  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true

  after_create :create_users_account

  protected

  def create_users_account
  	account = self.build_account
  	account.subscription_tier = 1
  	account.save
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :load_account

	def show

	end

	def edit

	end

	def update
		if params[:account][:subscription_tier] then
			@account.subscription_tier = params[:account][:subscription_tier]
			params[:account].delete('subscription_tier')
		end
		@account.update_attributes(params[:account])
		if @account.valid? then
			redirect_to account_path
		else
			render :edit
		end
	end

	protected

	def load_account
		@account = current_user.account
		if not @account then
			not_found!
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def not_found!
    raise ActionController::RoutingError.new('Not Found')
  end

  def after_sign_in_path_for(resource)
	'/account'
  end
end

app/controllers/file_sections_controller.rb
class FileSectionsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :load_page, only: [:create, :update, :destroy]
	before_filter :load_file_section, only: [:edit, :update, :destroy]


	def create
		@file_section = @page.file_sections.new(params[:file_section])
		authorize! :create, @file_section
		if @file_section.valid? then
			@file_section.save
			redirect_to page_path(@page)
		else
			render text: @file_section.errors.full_messages
		end
	end

	def edit
		authorize! :update, @file_section
	end

	def update
		authorize! :update, @file_section
		@file_section.update_attributes(params[:file_section])
		if @file_section.valid? then
			redirect_to page_path(@page)
		else
			render text: @file_section.errors.full_messages
		end
	end

	def destroy
		authorize! :destroy, @file_section
		@file_section.destroy
		redirect_to page_path(@page)
	end

	protected

	def load_page
		@page = Page.find_by_url(params[:page_id])
		if not @page then
			not_found!
		end
	end

	def load_file_section
		@file_section = FileSection.find_by_id(params[:id])
		if not @file_section then
			not_found!
		end
	end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
	before_filter :load_page, only: [:show, :edit, :update, :destroy]

	def new
		@page = Page.new
	end

	def show

	end

	def create
		@page = current_user.account.pages.new(params[:page])
		authorize! :create, @page
		if @page.valid? then
			@page.save
			redirect_to page_path(@page)
		else
			render :new
		end
	end

	def edit
		authorize! :update, @page
	end

	def update
		authorize! :update, @page
		@page.update_attributes(params[:page])
		if @page.valid? then
			redirect_to page_path(@page)
		else
			render :edit
		end
	end

	def destroy
		authorize! :destroy, @page
		@page.destroy
		redirect_to account_path
	end

	protected

	def load_page
		@page = Page.find_by_url(params[:id])
		if not @page then
			not_found!
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.haml
= semantic_form_for @account do |f|
	= f.inputs :subscription_tier
	= f.actions :submit, :cancel

app/views/accounts/show.html.haml
%p Pages
%br

- @account.pages.each do |page|
	= link_to page.title, page_path(page)
	%br
	= link_to "Edit Page", edit_page_path(page)
	= link_to "Delete Page", page_path(page), method: :delete
	%br
	%br

%br
%br

= link_to "Create New Page", new_page_path

%br

%br
= link_to "Edit Account", edit_account_path(@account)

app/views/file_sections/_file_section.html.haml
%p File Section
%p= file_section.title
%p= file_section.rank
= link_to "Edit File Section", edit_page_file_section_path(file_section.page, file_section)
%br
= link_to "Delete File Section", page_file_section_path(file_section.page, file_section), method: :delete
%br

app/views/file_sections/_form.html.haml
= semantic_form_for [page, file_section] do |f|
	= f.inputs :title, :rank
	= f.actions :submit, :cancel

app/views/file_sections/edit.html.haml
= render partial: 'form', locals: {page: @file_section.page, file_section: @file_section}

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Soapbox
		= stylesheet_link_tag    "application"
		/[if IE 6]
			=stylesheet_link_tag 'ie6'
		/[if IE 7]
			= stylesheet_link_tag 'ie7'
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		%p.notice= notice
		%p.alert= alert
		= yield

app/views/pages/_form.html.haml
= semantic_form_for @page do |f|
	= f.inputs :url, :contact_available, :title, :subtitle, :description
	= f.actions :submit, :cancel

app/views/pages/edit.html.haml
= render 'form'

app/views/pages/new.html.haml
= render 'form'

app/views/pages/show.html.haml
-# <<<<<<< HEAD
-# %p test
-# %p= @page.title

-# %p Existing file sections
-# - @page.file_sections.each do |file_section|
-# 	= render partial: 'file_sections/file_section', locals: {file_section: file_section}
-# %br

-# %p New file section
-# = render partial: 'file_sections/form', locals: {page: @page, file_section: FileSection.new}

-# = link_to "Edit Page", edit_page_path(@page)
-# = link_to "Delete Page", page_path(@page), method: :delete
-# =======
/ %p test
/ %p= @page.description


.first-section-wrapper
	%img#main-img{:src => "http://uncrate.com/p/2013/08/neat-ice-kit-xl.jpg", :alt => ""}/ 
.second-section-wrapper
	.nav-wrapper
		.nav.main-nav.float-right
			%ul 
				%li 
					%a{:href => ""} Contact
				%li.pipe &#124;
				- if current_user then				
					%li 
						= link_to "Log Out", destroy_user_session_path
				- else
					%li 
						= link_to "Admin Login", new_user_session_path

		.nav.main-nav.float-left
			%ul 
				%li 
					%a{:href => ""} Overview
				%li.pipe &#124;
				%li 
					%a{:href => ""} Downloads
	.content-wrapper
		.page-overview
			%h1.page-title= @page.title
			%h2.page-subtitle= @page.subtitle
			.divider
			%p= @page.description
.download-section-wrapper
	.content-wrapper
		%h2 These Are Downloads
		.divider
		.subsections-wrapper
			.subsection
				.subsection-header
					%h3 Subsection Title
					/ download button
					%a{:href => ""}
						%img.download-icon{:src => "http://clipartist.info/SVG/2011/December/download_icon-555px.png", :alt => ""}/  
				.resources-wrapper
					.resource
						%h4 Resouce Title
						%p Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
						/ download button
						%a{:href => ""}
							%img.download-icon{:src => "", :alt => ""}/   
					.resource
						%h4 Resouce Title
						%p Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac fa ipsum dolor sit amet, consectetur adipiscing elit.
						/ download button
						%a{:href => ""}
							%img.download-icon{:src => "", :alt => ""}/ 
		 
			.subsection
				.subsection-header
					%h3 Subsection Title
					/ download button
					%a{:href => ""}
						%img.download-icon{:src => "http://clipartist.info/SVG/2011/December/download_icon-555px.png", :alt => ""}/  
				.resources-wrapper
					.resource
						%h4 Resouce Title
						%p Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
						/ download button
						%a{:href => ""}
							%img.download-icon{:src => "", :alt => ""}/   
					.resource
						%h4 Resouce Title
						%p Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac fa ipsum dolor sit amet, consectetur adipiscing elit.
						/ download button
						%a{:href => ""}
							%img.download-icon{:src => "", :alt => ""}/ 
		 